### ISSUE TITLE
Auto close

### ISSUE THREAD

**Issue by xddxd** [pspatel321/thinkpad-auto-keyboard-backlight#1]
Hello! When I launch the program, it auto closes with an unhandled exception. Windows 10 1909 on a T440s.

<details><summary>Error code</summary>
Application: Auto Keyboard Backlight.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Auto_Keyboard_Backlight.Capture..ctor(Auto_Keyboard_Backlight.RawInput.RawInput)
   at Auto_Keyboard_Backlight.Timeout..ctor(Auto_Keyboard_Backlight.PowerManagement.PowerManagement, Auto_Keyboard_Backlight.RawInput.RawInput)
   at Auto_Keyboard_Backlight.App._Starting(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Auto_Keyboard_Backlight.App.Main()
   at Auto_Keyboard_Backlight.Program.Main()
</details>
<details><summary>Error Code</summary>
Faulting application name: Auto Keyboard Backlight.exe, version: 1.3.7262.26556, time stamp: 0x5dd44649
Faulting module name: KERNELBASE.dll, version: 10.0.19025.1, time stamp: 0xf2945738
Exception code: 0xe0434352
Fault offset: 0x0000000000035a29
Faulting process id: 0x2298
Faulting application start time: 0x01d59f12b40602eb
Faulting application path: C:\Program Files\Auto Keyboard Backlight\Auto Keyboard Backlight.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3a6be42f-2223-4001-96c5-beecae8052bb
Faulting package full name: 
Faulting package-relative application ID:
</details>

**Comment by xddxd** [comment]
I figured it out. It's because the Touchpad hardware ID is hardcoded in the program, changing it to the one in the T440s fixes the issue.
