### ISSUE TITLE
Faulting module KERNELBASE.dll

### ISSUE THREAD

**Issue by RobinEd** [pspatel321/thinkpad-auto-keyboard-backlight#10]
Faulting application name: Auto Backlight for ThinkPad.exe, version: 1.0.7451.2291, time stamp: 0x5ecca626
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x2f54
Faulting application start time: 0x01d6e5a6543d2659
Faulting application path: C:\Program Files\Auto Backlight for ThinkPad\Auto Backlight for ThinkPad.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e7e4b21c-9c50-4039-bfa6-ed66b47d5d12
Faulting package full name: 
Faulting package-relative application ID: 

So it doesn't start at all :'(
Using a X1 Yoga Gen5, win10 pro x64

**Comment by RJanata** [comment]
Same problem on X270, Windows 10 Pro x64 20H2.

> Application: Auto Backlight for ThinkPad.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Exception
>    at Auto_Backlight_for_ThinkPad.Capture..ctor(Auto_Backlight_for_ThinkPad.RawInput.RawInput)
>    at Auto_Backlight_for_ThinkPad.AutoKeyboardBacklightController..ctor(Auto_Backlight_for_ThinkPad.PowerManagement.PowerManagement, Auto_Backlight_for_ThinkPad.RawInput.RawInput)
>    at Auto_Backlight_for_ThinkPad.App..ctor()
>    at Auto_Backlight_for_ThinkPad.App.Main()
>    at Auto_Backlight_for_ThinkPad.Program.Main()

> Faulting application name: Auto Backlight for ThinkPad.exe, version: 1.0.7451.2291, time stamp: 0x5ecca626
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
> Exception code: 0xe0434352
> Fault offset: 0x000000000002d759
> Faulting process id: 0x5614
> Faulting application start time: 0x01d709c6a65d769d
> Faulting application path: C:\Program Files\Auto Backlight for ThinkPad\Auto Backlight for ThinkPad.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 014238f9-a5d4-45ac-970e-1d55e220f0ca
> Faulting package full name: 
> Faulting package-relative application ID:
