### ISSUE TITLE
Cannot get to work on Lenovo Flex 5 

### ISSUE THREAD

**Issue by MrFriske** [pspatel321/thinkpad-auto-keyboard-backlight#11]
System.Exception
  HResult=0x80131500
  Message=Failed to hook both Lenovo keyboard and mouse raw input devices
  Source=Auto Backlight for ThinkPad
  StackTrace:
   at Auto_Backlight_for_ThinkPad.Capture..ctor(RawInput ri)
   at Auto_Backlight_for_ThinkPad.AutoKeyboardBacklightController..ctor(PowerManagement pm, RawInput ri)
   at Auto_Backlight_for_ThinkPad.App..ctor()
   at Auto_Backlight_for_ThinkPad.App.Main()
   at Auto_Backlight_for_ThinkPad.Program.Main()

**Comment by Kazzymax** [comment]
Mine too. Please work on this. I would love to use it for keeping the backlight on. Lenovo having them time out makes absolutely no sense since it's how we're supposed to find the keys again in the first place in the dark.

**Comment by charettepa** [comment]
i also really need this to work
but i appear to have the opposite problem everyone else is reporting

mine never times out
it just stays on 24/7
i expect it to behave like every other laptop and timeout the backlight after 15-30 seconds

i struggle to understand why anyone would want it to stay on
