### ISSUE TITLE
Can't get it to work on ThinkPad X1 Extreme Gen 2

### ISSUE THREAD

**Issue by prat89** [pspatel321/thinkpad-auto-keyboard-backlight#2]
Hey, I've just installed Auto Backlight for ThinkPad on my ThinkPad X1 Extreme Gen 2 (Win 10) and I cannot get it to work. I do not see the tray icon at all. Could you please help me? Please let me know all the details you need.

**Comment by shakalys** [comment]
Same for P1 Gen 1(Win 10), Events shows error:
```
Application: Auto Backlight for ThinkPad.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Auto_Backlight_for_ThinkPad.WebCam+Cam..ctor()
   at Auto_Backlight_for_ThinkPad.AutoScreenBrightnessController..ctor(Auto_Backlight_for_ThinkPad.GlobalHotKey)
   at Auto_Backlight_for_ThinkPad.App..ctor()
   at Auto_Backlight_for_ThinkPad.App.Main()
   at Auto_Backlight_for_ThinkPad.Program.Main()

```
could someone provide older version msi

**Comment by Likicy** [comment]
its not working, install it on my X1 Carbon 7th gen, Win10, i7, I dont see the icon in the system tray.......
how do I find the setting?

**Comment by MartinLichtblau** [comment]
Doesn't show up anywhere on X1Y3; no GUI, no system tray.

**Comment by greg84** [comment]
I've run the debugger on my X1 Extreme Gen 2.

- The mouse (trackpad) has a different path value to what the code in Capture.cs is expecting. Mine is: `ACPI#LEN0402` 
- The web cam MonikerString value is also different so it crashes in the constructor for WebCam.cs too.

I would suggest [these changes](https://github.com/pspatel321/auto-backlight-for-thinkpad/pull/8) could make it compatible with more devices, but I'm not able to test this with any other models.

**Comment by jmlag** [comment]
> I would suggest [these changes](https://github.com/pspatel321/auto-backlight-for-thinkpad/pull/8) could make it compatible with more devices, but I'm not able to test this with any other models.

@greg84 I'm on an X1 Yoga 3rd Gen. and my paths are different from both yours and the original repo. I got it to work after changing the values.

**Comment by greg84** [comment]
@jmlag what values do you have? We might be able to change my PR so it's more compatible.

**Comment by jmlag** [comment]
@greg84 LEN009A for the mouse and vid_04f2&pid_b61e for the webcam.

I don't code in C# but surely there must be a way to get these values without hard coding them in. And it would probably be better to display an error message instead of throwing an exception which prevents the program from starting up at all.
