### ISSUE TITLE
Cannot get it to load on P73

### ISSUE THREAD

**Issue by nate104** [pspatel321/thinkpad-auto-keyboard-backlight#4]
I'm unable to successfully load the program on my P73 running Win10 Pro 1909. If it's of any value, I see the following two errors in the event viewer:

Application Error
------------------
Faulting application name: Auto Backlight for ThinkPad.exe, version: 1.0.7428.6847, time stamp: 0x5eae7740
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0xb89efff3
Exception code: 0xe0434352
Fault offset: 0x000000000003a799
Faulting process id: 0x1f1c
Faulting application start time: 0x01d62e84674ab296
Faulting application path: C:\Program Files\Auto Backlight for ThinkPad\Auto Backlight for ThinkPad.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9b14eb7f-349d-402a-9bc7-888ccfd414c8
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime
-------------------
Application: Auto Backlight for ThinkPad.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Auto_Backlight_for_ThinkPad.Capture..ctor(Auto_Backlight_for_ThinkPad.RawInput.RawInput)
   at Auto_Backlight_for_ThinkPad.AutoKeyboardBacklightController..ctor(Auto_Backlight_for_ThinkPad.PowerManagement.PowerManagement, Auto_Backlight_for_ThinkPad.RawInput.RawInput)
   at Auto_Backlight_for_ThinkPad.App..ctor()
   at Auto_Backlight_for_ThinkPad.App.Main()
   at Auto_Backlight_for_ThinkPad.Program.Main()

**Comment by nate104** [comment]
It appears most of the issues others have submitted may be similar to mine where the program simply isn't loading. I hope that the information in my original post is helpful. This app seems to be exactly what I'm looking for, so I'd love to contribute anything to help improve it.
